@isTest
public class tripulacionRequeridaTest {
    
    /*@TestSetup
    static void makeData(){
        contacto cto = new Contact(LastName = 'auxiliarprueba',
                                        RecordTypeId = '');
        insert.cto;

        Avion__c av = new Avion__c(Tipo__c = 'Airbus A330');
        insert av;

            List<Product2> vuelos = new List<Product2>();
            for(integer i = 0; i < 20; i++){
                Product2 vuelo = new Product2(Name = 'Av-'+i, 
                                                Fecha_y_hora_de_partida__c = DateTime.now()+1, 
                                                Fecha_y_hora_estimada_de_llegada__c = (DateTime.now()+1).addHours(5),
                                                estado__c = 'En venta',
                                                isActive = true,
                                                Avion__c = av.Id);
                vuelos.add(vuelo);
            }
            insert vuelos;

            List<vueloXcontacto__c> vxc = new List<vueloXcontacto__c>();
            for(Product2 v : vuelos){
                vueloXcontacto__c aux = nre vueloXcontacto__c(Contacto__c = cto.Id
                                                                Vuelo__c = v.Id);
                vxc.add(aux);
            }
            insert vxc;
    }

    @isTest
    private static void ingresoVueloExitoso() {
        
    }
    @isTest
    private static void name() {
        
    }
    @isTest
    private static void name() {
        
    }   */
}
